# Generated by Django 4.1.2 on 2022-10-14 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0003_alter_artist_options_remove_artist_stage_name_and_more'),
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albums',
            name='creation',
        ),
        migrations.RemoveField(
            model_name='albums',
            name='release_datetime',
        ),
        migrations.AddField(
            model_name='albums',
            name='ax',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artists.artist'),
        ),
        migrations.AlterField(
            model_name='albums',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='albums',
            name='name',
            field=models.CharField(default='New Album', max_length=100),
        ),
    ]
