# Generated by Django 4.1.2 on 2022-10-14 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_remove_albums_creation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='albums',
            old_name='ax',
            new_name='artist',
        ),
    ]
