# Generated by Django 4.1.2 on 2022-10-14 15:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_rename_ax_albums_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='albums',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
