# Generated by Django 4.1.2 on 2022-10-14 15:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0004_albums_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='albums',
            name='release_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
