# Generated by Django 4.1.2 on 2022-10-14 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0005_albums_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albums',
            name='release_date',
            field=models.DateTimeField(),
        ),
    ]
