# Generated by Django 4.1.2 on 2022-10-18 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0006_alter_albums_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='albums',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
