# Generated by Django 4.1.2 on 2022-10-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0007_albums_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albums',
            name='approved',
            field=models.BooleanField(default=False, help_text='Approve the album if its name is not explicit'),
        ),
    ]
