# Generated by Django 4.1.2 on 2022-10-18 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0008_alter_albums_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albums',
            name='approved',
        ),
        migrations.AddField(
            model_name='albums',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
