# Generated by Django 4.1.2 on 2022-10-18 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0009_remove_albums_approved_albums_is_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='albums',
            old_name='is_approved',
            new_name='approved',
        ),
    ]
