# Generated by Django 4.1.2 on 2022-10-28 20:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0013_alter_song_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='audio',
            field=models.FileField(upload_to='files', validators=[django.core.validators.FileExtensionValidator(['mp3', 'wav'])]),
        ),
    ]
