# Generated by Django 4.1.2 on 2022-10-14 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_alter_artist_stage_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ('Stage_name',)},
        ),
        migrations.RemoveField(
            model_name='artist',
            name='stage_name',
        ),
        migrations.AlterField(
            model_name='artist',
            name='Social_link',
            field=models.URLField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='Stage_name',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
