# Generated by Django 4.1.2 on 2022-10-14 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0003_alter_artist_options_remove_artist_stage_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='Stage_name',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
