# Generated by Django 4.1.2 on 2022-10-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0004_alter_artist_stage_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='Social_link',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='artist',
            name='Stage_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
