# Generated by Django 4.1.2 on 2022-10-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0005_alter_artist_social_link_alter_artist_stage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='approved_albums',
            field=models.IntegerField(default=0),
        ),
    ]
