# Generated by Django 4.1.2 on 2022-10-19 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0006_artist_approved_albums'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='approved_albums',
        ),
    ]
